# Generated by Django 3.1.3 on 2020-11-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
